services:
  - type: web
    name: welldent-clinic-frontend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node static-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

